export default {
  NSQPR_PASSPORT_DESERIALIZEUSER: `BEGIN  NSQPR_PASSPORT_LOGIN_LOCAL(:id_user, :cursor); END;`,
  NSQPR_PASSPORT_LOGIN_LOCAL: `BEGIN  NSQPR_PASSPORT_LOGIN_LOCAL(:id_user, :cursor); END;`,

  NSQPR_LOGIN_SUCCESS: `BEGIN  NSQPR_LOGIN_SUCCESS(:id_user); END;`,
  NSQPR_LOGIN_FAIL: `BEGIN  NSQPR_LOGIN_FAIL(:id_user); END;`,
};
